- job:
    name: juju-destroy-environment
    defaults: global
    properties:
      - build-discarder:
          num-to-keep: 3
    builders:
      - shell: |
          #!/bin/bash -e
          juju destroy-environment -y amazon
